# Generated by Django 5.0.6 on 2024-06-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Имя'),
        ),
    ]
