# Generated by Django 5.0.6 on 2024-07-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20240702_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='test_1',
            field=models.CharField(default=22, max_length=100),
            preserve_default=False,
        ),
    ]
