# Generated by Django 5.0.6 on 2024-07-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_measurement_test_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='test_1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
